export default [
	{alias: 'Euro', value: 'EUR'},
	{alias: 'Thai baht', value: 'THB'},
	{alias: 'Swiss franc', value: 'CHF'},
	{alias: 'Czech koruna', value: 'CZK'},
	{alias: 'Danish krone', value: 'DKK'},
	{alias: 'Indian rupee', value: 'INR'},
	{alias: 'Mexican peso', value: 'MXN'},
	{alias: 'Polish złoty', value: 'PLN'},
	{alias: 'Russian ruble', value: 'RUB'},
	{alias: 'Swedish krona', value: 'SEK'},
	{alias: 'Brazilian real', value: 'BRL'},
	{alias: 'Japanese yen 1', value: 'JPY'},
	{alias: 'Pound sterling', value: 'GBP'},
	{alias: 'Canadian dollar', value: 'CAD'},
	{alias: 'Norwegian krone', value: 'NOK'},
	{alias: 'Philippine peso', value: 'PHP'},
	{alias: 'Hong Kong dollar', value: 'HKD'},
	{alias: 'Singapore dollar', value: 'SGD'},
	{alias: 'Australian dollar', value: 'AUD'},
	{alias: 'Hungarian forint 1', value: 'HUF'},
	{alias: 'Israeli new shekel', value: 'ILS'},
	{alias: 'New Zealand dollar', value: 'NZD'},
	{alias: 'Malaysian ringgit 2', value: 'MYR'},
	{alias: 'New Taiwan dollar 1', value: 'TWD'},
	{alias: 'United States dollar', value: 'USD'},
];